import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        translation: {
          home: "Home",
          buy: "Buy",
          sell: "Sell",
          donate: "Donate",
          AcceptEquipment:"Accept Equipment",
          services: "Services",
          maintenance_page: "Maintenance Request",
          inspection: "Inspection",
          service3: "Service 3",
          signinBtn: "Sign In",
          logout: "Logout",
          medtrade: "MedTrade",
          footerDescription: "Making healthcare more sustainable and accessible through equipment reuse and recycling.",
          buyEquipment: "Buy Equipment",
          sellEquipment: "Sell Equipment",
          donateEquipment: "Donate Equipment",
          equipmentValuation: "Equipment Valuation",
          sustainabilityReports: "Sustainability Reports",
          company: "Company",
          aboutUs: "About Us",
          ourMission: "Our Mission",
          blog: "Blog",
          press: "Press",
          careers: "Careers",
          support: "Support",
          contactUs: "Contact Us",
          faqs: "FAQs",
          shippingInfo: "Shipping Info",
          privacyPolicy: "Privacy Policy",
          termsOfService: "Terms of Service",
          copyright: "All rights reserved. A sustainable healthcare initiative.",
          hero: {
            title: "Sustainable Healthcare Equipment Marketplace",
            description: "Buy, sell, or donate medical equipment while reducing waste and making healthcare more accessible.",
            browseButton: "Browse Equipment",
            listButton: "List Equipment"
          },
          impact: {
            title: "Our Collective Impact",
            description: "Together we're making healthcare more sustainable and accessible around the world.",
            equipmentValue: "Equipment value recirculated",
            co2Emissions: "Tons of CO₂ emissions prevented",
            medicalFacilities: "Medical facilities equipped"
          },
          howItWork: {
            title: "How MedTrade Works",
            description: "Our platform makes it easy to buy, sell, or donate medical equipment while promoting sustainability.",
            steps: {
              list: {
                title: "List Your Equipment",
                description: "Create detailed listings for medical equipment you want to sell or donate. Include photos, specifications, and pricing."
              },
              connect: {
                title: "Connect with Buyers/Sellers",
                description: "Our secure messaging system allows healthcare providers to communicate directly with sellers to ask questions."
              },
              secure: {
                title: "Secure Transaction",
                description: "Complete your purchase through our secure payment system with equipment verification and shipping coordination."
              }
            },
            ready: {
              title: "Ready to Get Started?",
              description: "Join thousands of healthcare professionals who are making a difference through sustainable medical equipment practices.",
              createAccount: "Create Account",
              learnMore: "Learn More"
            }
          },
          signUpAction: {
            title: "Join the Medical Equipment Revolution",
            description: "Help create a more sustainable and accessible healthcare system by buying, selling, or donating through MedTrade.",
            signUpNow: "Sign Up Now",
            contactUs: "Contact Us"
          },
          chat: {
            title: "Medical Equipment Support",
            minimize: "Minimize chat",
            close: "Close chat",
            open_chat: "Open support chat",
            input_placeholder: "Type your message...",
            send: "Send message",
            agent_role: "Medical Equipment Specialist",
            response: {
              ventilator: "I see you're looking for respiratory equipment. We have several ventilator models available. Would you like assistance finding the right one for your needs?",
              ultrasound: "Our platform has various ultrasound and imaging equipment options. I suggest checking the Diagnostic Equipment category or submitting a specific request form.",
              survey: "You can complete our health survey in your profile page. This helps us recommend equipment tailored to your specific needs.",
              price: "We offer equipment at various price points. Many sellers also accept payment plans or have donation programs for those with financial constraints.",
              donate: "We appreciate your generosity! You can donate unused medical equipment through our donation page.",
              buy: "Looking to buy equipment? You can browse our marketplace or request specific items based on your needs.",
              sell: "Great! You can list your unused equipment for sale under the Sell Equipment section. Need help with that?",
              agent_connect: "I'll connect you with a human agent for more specialized help. Please wait a moment...",
              agent_welcome: "Hello! This is Dr. Sarah Thompson, your Medical Equipment Specialist. How can I assist you today?",
              default: "Sorry, I didn’t understand that. Could you please rephrase or ask about our medical equipment?"
            },
            suggestions: {
              ventilator: "Looking for ventilators or breathing machines",
              ultrasound: "Ultrasound or imaging equipment",
              price: "Questions about prices or affordability",
              agent: "Connect me to a human agent",
              survey: "Help with the health survey",
              donate: "I want to donate equipment",
              buy: "I want to buy equipment",
              sell: "I want to sell equipment"
            }
          },
          help: {
            title: "Need Help?",
            description: "For help, please contact"
          }, 
          "featuredEquipment": "Featured Equipment",
          "details": "Details",
          "free": "Free",
          "viewAllEquipment": "View All Equipment",
          "addEquipment": "Add Equipment",
          "allEquipment":"All Equipment",
          "condition": {
  "brandNew": "Brand new",
  "likeNew": "Like new",
  "Used- good": "Used - good",
  "usedNeedsRepair": "Used - needs repair",
  "notWorking": "Not working"
},
  "signUp": "Sign Up",
  "registrationFailed": "Registration failed. Please check your input.",
  "somethingWentWrong": "Something went wrong.",
  "firstNameRequired": "First name is required",
  "firstNameLettersOnly": "First name must contain only letters",
  "firstNameMin": "First name must be at least 2 characters",
  "lastNameRequired": "Last name is required",
  "lastNameLettersOnly": "Last name must contain only letters",
  "lastNameMin": "Last name must be at least 2 characters",
  "emailRequired": "Email is required",
  "emailValid": "Please enter a valid email",
  "passwordRequired": "Password is required",
  "passwordMin": "Password must be at least 8 characters long",
  "passwordLetter": "Password must contain at least one letter",
  "passwordNumber": "Password must contain at least one number",
  "passwordConfirmRequired": "Please confirm your password",
  "passwordsMustMatch": "Passwords must match",
  "phoneRequired": "Phone number is required",
  "phoneNumbersOnly": "Phone must contain only numbers",
  "phoneMin": "Phone must be at least 11 digits",
  "addressRequired": "Address is required",
  "addressMin": "Address must be at least 5 characters",
  "cityRequired": "City is required",
  "stateRequired": "State is required",
  "zipRequired": "ZIP code is required",
  "zipDigits": "ZIP code must be 4–10 digits",
  "countryRequired": "Country is required",
  "alreadyHaveAccount": "Already have an account?",
  "login": "Login",
  "fields": {
    "first_name": "First Name",
    "last_name": "Last Name",
    "email": "Email",
    "password": "Password",
    "password_confirmation": "Confirm Password",
    "phone": "Phone",
    "address": "Address",
    "city": "City",
    "state": "State",
    "ZIP_code": "ZIP Code",
    "country": "Country"
  }
          ,"signin": {
    "title": "Sign In",
    "email": "Email",
    "password": "Password",
    "submit": "Sign In",
    "loading": "Loading...",
    "success": "Login successful",
    "error": "Invalid email or password",
    "noAccount": "Don't have an account?",
    "register": "Sign Up"
  },
  "validation": {
    "required": "is required",
    "email": "Enter a valid email",
    "minChars": "Must be at least {{count}} characters"
   
  }, 
  "addequipment": {
    "title": "Add Equipment",
    "titleLabel": "Title",
    "titlePlaceholder": "Enter equipment title",
    "descLabel": "Description",
    "descPlaceholder": "Write a short description",
    "priceLabel": "Price (in EGP)",
    "pricePlaceholder": "Enter equipment price",
    "conditionLabel": "Condition",
    "conditionPlaceholder": "Select condition", "feeMessage": "A fee will be charged:",
  "confirmSubmit": "Do you want to continue?",
  "cancelledByUser": "Submission was cancelled by the user.",
  "invalidPrice": "Please enter a valid price.",
    condition: {
      "brandNew": "Brand new",
      "likeNew": "Like new",
      "usedGood": "Used - good",
      "usedNeedsRepair": "Used - needs repair",
      "notWorking": "Not working"
    },
    "categoryLabel": "Category",
    "categoryPlaceholder": "Select category",
    "categories": {
      "beds": "Hospital Beds & Stretchers",
      "vital": "Vital Signs & Monitoring Devices",
      "mobility": "Mobility Support Equipment",
      "dental": "Dental Care Equipment",
      "diagnostic": "Basic Diagnostic Tools",
      "lab": "Lab & Testing Devices",
      "imaging": "Imaging & Radiology Devices",
      "respiratory": "Respiratory Support Devices",
      "iv": "IV & Fluid Administration",
      "sterilization": "Sterilization & Disinfection Tools",
      "emergency": "Emergency & Life Support Equipment",
      "rehabilitation": "Rehabilitation & Therapy Tools",
      "infant": "Infant & Newborn Care",
      "others": "Others"
    },
    "donationLabel": "Donation",
    "donationPlaceholder": "Is this a donation?",
    "donation": {
      "yes": "Yes, donation",
      "no": "No, for sale"
    },
    "mainImageLabel": "Main Image",
    "mainImageRequired": "Main image is required.",
    "optionalImage": "Optional Image {{num}}",
    "submit": "Submit",
    "cancel": "Cancel",
    "loading": "Uploading...",
    "success": "Equipment added successfully!",
    "error": "Failed to add equipment.",
    "somethingWrong": "Something went wrong. Please try again."
  }, back: "Back",
  loadingFailed: "Failed to load data",
  productNotFound: "Product not found",
  postedOn: "Posted on:",
  buyNow: "Buy Now",
  contactSeller: "Contact Seller",
  contactUnderDevelopment: "Contact feature under development",
  additionalImage: "Additional image",
  toggleLang: "عربي",
  loading: "Loading...",
  return: "Return",
  errorMsg: "Failed to load data",
  
  "category": "Category",
  "addedBy": "Added By",
  "name": "Name",
  "email": "Email",
  "phone": "Phone",
  "address":"Address",
  "productNotFound": "Product not found",
  "loadingFailed": "Failed to load product data",
  "loading": "Loading...",
  "return": "Return",
  "postedOn": "Posted on",
  "buyNow": "Buy Now",
  "contactSeller": "Contact Seller",
  "additionalImage": "Additional Image",
  "feedback": "Feedback",
  "seller": "Seller",
 
 "Profile":"My Profile",
  "myProfile": {
    "confirm_delete": "Are you sure you want to delete this product?",
    "delete_failed": "Failed to delete product",
    "product_image": "Product image",
    "price": "Price",
    "status": "Status",
    "availability": "Availability",
    "posted_on": "Posted on",
    "marking": "Marking...",
    "mark_as_sold": "Mark as Sold",
    "deleting": "Deleting...",
    "delete": "Delete",
    "no_products": "You have no products listed yet.",
    "survey_form": "Survey Form",
    "coming_soon": "{{component}} coming soon",
    "wallet_balance": "Wallet Balance",
    "guest_user": "Guest User",
    "browsing_as_guest": "Browsing as a guest",
    "email": "Email",
    "phone": "Phone",
    "wallet": "Wallet",
    "joined": "Joined",
    "listings": "Listings",
    "messages": "Messages",
    "orders": "Orders",
    "wallet": "Wallet",
    "request": "Request",
    "survey": "Survey",
    "ai_suggestion": "AI Suggestion",
    "community": "Community",
  "no_ai_suggestions": "No suggestions found",
  "price": "Price",
  "category": "Category",
  "available": "Availability"
  },
  "survey": {
    "age": "Age",
    "gender": "Gender",
    "select": "Select",
    "male": "Male",
    "female": "Female",
    "primary_medical_condition": "Primary Medical Condition",
    "health_care_provider": "Health Care Provider",
    "mobility_level": "Mobility Level",
    "medical_equipment": "Medical Equipment",
    "duration_of_need": "Duration of Need",
    "submitting": "Submitting...",
    "submit": "Submit",
    "equipment": {
      "beds": "Hospital Beds & Stretchers",
      "monitoring": "Vital Signs & Monitoring Devices",
      "mobility_support": "Mobility Support Equipment",
      "dental": "Dental Care Equipment",
      "diagnostics": "Basic Diagnostic Tools",
      "lab": "Lab & Testing Devices",
      "imaging": "Imaging & Radiology Devices",
      "respiratory": "Respiratory Support Devices",
      "iv_fluid": "IV & Fluid Administration",
      "sterilization": "Sterilization & Disinfection Tools",
      "emergency": "Emergency & Life Support Equipment",
      "rehabilitation": "Rehabilitation & Therapy Tools",
      "infant_care": "Infant & Newborn Care",
      "others": "Others"
    }
  },
  "filterProducts": "Filter Products",
  "allCategories": "All Categories",
  "mobilitySupport": "Mobility Support Equipment",
  "emergencySupport": "Emergency & Life Support Equipment",
  "walker": "Walker",
  "hospitalBeds": "Hospital Beds & Stretchers",
  "respiratorySupport": "Respiratory Support Devices",
  "labTesting": "Lab & Testing Devices",
  "vitalSigns": "Vital Signs & Monitoring Devices",
  "rehabilitation": "Rehabilitation & Therapy Tools",
  "dentalCare": "Dental Care Equipment",
  "allConditions": "All Conditions",
  "brandNew": "Brand new",
  "likeNew": "Like new",
  "usedGood": "Used - good",
  "usedNeedsRepair": "Used - needs repair",
  "notWorking": "Not working",
  "minPrice": "Min Price",
  "maxPrice": "Max Price",
  "priceLowToHigh": "Price: Low to High",
  "priceHighToLow": "Price: High to Low",
  "apply": "Apply",
  "reset": "Reset",
  "noProductsFound": "No products found for selected filters.",
  "noTitle": "No Title",
  "category": "Category",
  "condition_2": "Condition",
  "price": "Price",
  "na": "N/A",
  "donationForm": {
    "header": "NGO Donation Request",
    "ngoName": "NGO Name",
    "ngoNameHelp": "Enter the name of the requesting NGO",
    "itemName": "Item Name",
    "itemNameHelp": "Enter the name of the item to donate",
    "description": "Description",
    "descriptionHelp": "Describe the condition and use of the item",
    "quantity": "Quantity",
    "quantityHelp": "Minimum quantity is 1",
    "image": "Upload Image",
    "imageHelp": "Optional. Only PNG, JPG, JPEG formats accepted.",
    "submit": "Submit",
    "cancel": "Cancel",
    "loading": "Submitting...",
    "success": "Donation submitted successfully!",
    "error": "Failed to submit donation. Please try again."
  }, "contactTitle": "Contact {{name}}",
  "seller": "Seller",
  "loadingMessages": "Loading messages...",
  "noPreviousMessages": "No previous messages.",
  "you": "You",
  "defaultMessage": "Hi, I'm interested in your {{title}}. Is it still available?",
  "sendMessage": "Send Message",
  "sending": "Sending...",
"reportProblem": "Report a Problem",
"describeProblem": "Please describe the issue...",
"pleaseWriteSomething": "Please write something before submitting.",
"submitReport": "Submit Report",
"cancel": "Cancel",
"reportSent": "Your report has been sent. Thank you!",
"reportFailed": "Failed to send report. Please try again later.",
 "giveFeedback": "Give Feedback",
  "feedbackPlaceholder": "Write your feedback here...",
  "feedbackThanks": "Thanks for your feedback!",
  "enterFeedback": "Please enter your feedback before submitting.",
  "submit": "Submit",
  "cancel": "Cancel"
, "report": {
    "title": "Admin Reports Dashboard",
    "loading": "Loading reports...",
    "loadError": "Failed to load reports. Please try again later.",
    "noReports": "No reports available.",
    "listHeader": "Reports List",
    "user": "User",
    "report": "Report",
    "createdAt": "Created At"
  },
  
  "missingProductInfo": "Missing product information.",
  "failedToLoadCheckout": "Failed to load checkout info.",
  "pleaseFillFields": "Please fill all required fields correctly",
  "orderSuccessWallet": "Order completed successfully!",
  "orderSuccessWalletPartial": "Order completed successfully! You paid ${{amount}} from other source.",
  "walletPaymentFailed": "Wallet payment failed. Please try another payment method.",
  "orderSuccessCOD": "Order placed successfully (Cash on Delivery)!",
  "addressUpdateFailed": "Failed to update address.",
  "checkoutFailed": "Something went wrong during checkout. Please try again.",
  "loadingCheckout": "Loading checkout info...",
  "checkoutTitle": "Checkout",
  "shippingInfo": "Shipping Information",
  "fullName": "Full Name",
  "email": "Email",
  "address": "Address",
  "city": "City",
  "state": "State",
  "zipCode": "ZIP Code",
  "zipNumeric": "ZIP Code must be numeric",
  "country": "Country",
  "selectCountry": "Select Country",
  "egypt": "Egypt",
  "paymentMethod": "Payment Method",
  "wallet": "Wallet",
  "balance": "Balance",
  "add": "Add",
  "cashOnDelivery": "Cash on Delivery (COD)",
  "processing": "Processing...",
  "placeOrder": "Place Order",
  "orderSummary": "Order Summary",
  "subtotal": "Subtotal",
  "shipping": "Shipping",
  "total": "Total",
  "sellerInfo": "Seller Information",
  "name": "Name",
  
  "maintenanceRequest": "Maintenance Request",
  "title": "Title",
  "productDesc": "Product Description",
  "problemDesc": "Problem Description",
  "phone": "Phone",
  "address": "Address",
  "submitRequest": "Submit Request",
    "confirmMaintenance": "The maintenance fee is 300 EGP. Do you want to proceed?"
,
  "maintenance": {
  "header": "Maintenance Requests",
  "loading": "Loading maintenance requests...",
  "loadError": "Failed to load maintenance data.",
  "noRequests": "No maintenance requests available.",
  "listHeader": "Maintenance Request List",
  "user": "User",
  "title": "Title",
  "address": "Address",
  "phone": "Phone",
  "productDesc": "Product Description",
  "problemDesc": "Problem Description",
  "createdAt": "Date Created"
},
"AllOrders":"All Orders",
"ShowMantiance":"Show Mantiance Requests",
"SubscriptionPage":"Subscription",
"SubscriptionRequest":"Subscription Request",

  "orders": {
    "title": "All Orders",
    "loading": "Loading orders...",
    "loadError": "Failed to load orders. Please try again later.",
    "noOrders": "There are currently no orders.",
    "listHeader": "Orders List",
    "orderId": "Order ID",
    "userId": "User ID",
    "productId": "Product ID",
    "condition": "Condition",
    "subscription": "Subscription",
    "payment": "Payment",
    "date": "Order Date"
  }, "subscription": {
    "title": "Subscription Information",
    "detailsHeader": "User Subscription Details",
    "id": "ID",
    "name": "Name",
    "email": "Email",
    "phone": "Phone",
    "wallet": "Wallet",
    "address": "Address",
    "city": "City",
    "country": "Country",
    "created_at": "Created At",
    "loading": "Loading subscription data...",
    "error": "Failed to load subscription information"
  },
  
  "DonationRequests": "NGO Donation Requests",
  "viewAllDonationRequests": "View All NGO Donation Requests",
  "description": "Description",
  "ngoName": "NGO Name",
  "quantity": "Quantity",
  "status": "Status",
  "free": "Free",
  "noDescription": "No description available",
  "donateOne": "Donate +1",
  "donationSuccess": "Donation successful!",
  "donationFailed": "Donation failed. Please try again.",
  "AcceptNgoRequest":"Accept NGO Donation Requests",

  "inspection": {
    "title": "Inspection",
    "heading": "Inspection Service",
    "description": "We offer a trusted equipment inspection service to ensure quality and safety.",
    "fee": "Fee: 70 EGP",
    "contactMessage": "If you want to inspect an equipment, please contact us:",
    "contactButton": "Contact Us at MedTrade@gmail.com"
  }  ,
  
  "wallet": {
    "title": "Pay with Paymob",
    "emailLabel": "Email",
    "emailPlaceholder": "Enter your email",
    "amountLabel": "Amount (EGP)",
    "amountPlaceholder": "Enter amount to pay",
    "payNow": "Pay Now",
    "loading": "Processing...",
    "validationError": "Please enter a valid email and amount",
    "paymentFailed": "Payment failed",
    "unknownError": "An unknown error occurred",
    "urlError": "Missing valid email or amount in URL"
  },
  "WalletRecharge":"Wallet Recharge"
        },
        
         
      },
      ar: {
        translation: {
          home: "الرئيسية",
          buy: "شراء",
          sell: "بيع",
          donate: "تبرع",
                    AcceptEquipment:"قبول الجهاز",

          services: "الخدمات",
          maintenance_page: "طلب صيانه",
          inspection: "فحص",
          service3: "خدمة ٣",
          signinBtn: "تسجيل الدخول",
          logout: "تسجيل الخروج",
          medtrade: "ميد تريد",
          footerDescription: "نجعل الرعاية الصحية أكثر استدامة وسهولة من خلال إعادة استخدام وإعادة تدوير المعدات.",
          buyEquipment: "شراء المعدات",
          sellEquipment: "بيع المعدات",
          donateEquipment: "التبرع بالمعدات",
          equipmentValuation: "تقييم المعدات",
          sustainabilityReports: "تقارير الاستدامة",
          company: "الشركة",
          aboutUs: "معلومات عنا",
          ourMission: "مهمتنا",
          blog: "المدونة",
          press: "الصحافة",
          careers: "الوظائف",
          support: "الدعم",
          contactUs: "اتصل بنا",
          faqs: "الأسئلة الشائعة",
          shippingInfo: "معلومات الشحن",
          privacyPolicy: "سياسة الخصوصية",
          termsOfService: "شروط الخدمة",
          copyright: "جميع الحقوق محفوظة. مبادرة رعاية صحية مستدامة.",
          hero: {
            title: "سوق المعدات الطبية المستدامة",
            description: "اشترِ أو بع أو تبرع بالمعدات الطبية مع تقليل الهدر وجعل الرعاية الصحية أكثر سهولة.",
            browseButton: "تصفح المعدات",
            listButton: "أدرج المعدات"
          },
          impact: {
            title: "أثرنا الجماعي",
            description: "معًا نجعل الرعاية الصحية أكثر استدامة وتيسيرًا في جميع أنحاء العالم.",
            equipmentValue: "قيمة المعدات المعاد تدويرها",
            co2Emissions: "الأطنان من انبعاثات ثاني أكسيد الكربون الممنوعة",
            medicalFacilities: "المرافق الطبية المجهزة"
          },
          howItWork: {
            title: "كيف يعمل ميد تريد",
            description: "منصتنا تجعل من السهل شراء أو بيع أو التبرع بالمعدات الطبية مع تعزيز الاستدامة.",
            steps: {
              list: {
                title: "أدرج معداتك",
                description: "قم بإنشاء قوائم مفصلة للمعدات الطبية التي ترغب في بيعها أو التبرع بها. أضف صورًا، المواصفات، والأسعار."
              },
              connect: {
                title: "تواصل مع المشترين/البائعين",
                description: "نظام المراسلة الآمن لدينا يسمح لمقدمي الرعاية الصحية بالتواصل المباشر مع البائعين لطرح الأسئلة."
              },
              secure: {
                title: "معاملة آمنة",
                description: "أكمل عملية الشراء من خلال نظام الدفع الآمن مع التحقق من المعدات وتنسيق الشحن."
              }
            },
            ready: {
              title: "هل أنت مستعد للبدء؟",
              description: "انضم إلى آلاف المتخصصين في الرعاية الصحية الذين يصنعون فرقًا من خلال ممارسات المعدات الطبية المستدامة.",
              createAccount: "إنشاء حساب",
              learnMore: "تعرف أكثر"
            }
          },
          signUpAction: {
            title: "انضم إلى ثورة المعدات الطبية",
            description: "ساعد في خلق نظام رعاية صحية أكثر استدامة وسهولة من خلال الشراء أو البيع أو التبرع عبر ميد تريد.",
            signUpNow: "سجل الآن",
            contactUs: "اتصل بنا"
          },
          chat: {
            title: "دعم المعدات الطبية",
            minimize: "تصغير المحادثة",
            close: "إغلاق المحادثة",
            open_chat: "فتح المحادثة",
            input_placeholder: "اكتب رسالتك...",
            send: "إرسال الرسالة",
            agent_role: "أخصائي معدات طبية",
            response: {
              ventilator: "أرى أنك تبحث عن أجهزة التنفس. لدينا عدة موديلات من أجهزة التنفس الصناعي. هل تريد المساعدة في اختيار الأنسب لك؟",
              ultrasound: "يحتوي منصتنا على مجموعة متنوعة من أجهزة الموجات فوق الصوتية والتصوير. أنصحك بالاطلاع على قسم أجهزة التشخيص أو إرسال طلب خاص.",
              survey: "يمكنك إكمال الاستبيان الصحي من صفحة ملفك الشخصي. هذا يساعدنا على تقديم توصيات مناسبة لاحتياجاتك.",
              price: "نقدم معدات بأسعار مختلفة. العديد من البائعين يقبلون خطط الدفع أو لديهم برامج تبرع لمن يحتاجون دعمًا ماليًا.",
              donate: "نقدّر سخائك! يمكنك التبرع بالمعدات الطبية غير المستخدمة من خلال صفحة التبرع.",
              buy: "هل ترغب في شراء معدات؟ يمكنك تصفح السوق أو طلب عناصر معينة حسب حاجتك.",
              sell: "رائع! يمكنك عرض معداتك غير المستخدمة للبيع في قسم البيع. هل تحتاج مساعدة في ذلك؟",
              agent_connect: "سأربطك بوكيل بشري لمساعدتك بشكل أفضل. يرجى الانتظار...",
              agent_welcome: "مرحبًا! أنا د. سارة طومسون، أخصائية المعدات الطبية. كيف يمكنني مساعدتك اليوم؟",
              default: "عذرًا، لم أفهم ما قلته. هل يمكنك إعادة الصياغة أو السؤال عن معداتنا الطبية؟"
            },
            suggestions: {
              ventilator: "أبحث عن أجهزة التنفس أو أجهزة التنفس الصناعي",
              ultrasound: "معدات الموجات فوق الصوتية أو التصوير",
              price: "أسئلة عن الأسعار أو القدرة على الدفع",
              agent: "أريد التحدث مع وكيل بشري",
              survey: "مساعدة في الاستبيان الصحي",
              donate: "أرغب في التبرع بالمعدات",
              buy: "أرغب في شراء المعدات",
              sell: "أرغب في بيع المعدات"
            }
          },
          help: {
            title: "هل تحتاج مساعدة؟",
            description: "للمساعدة، يرجى التواصل مع"
          },"featuredEquipment": "الأجهزة المميزة",
  "details": "التفاصيل",
  "free": "مجانًا",
  "viewAllEquipment": "عرض كل الأجهزة",
  "addEquipment": "إضافة منتج",
  "allEquipment":"كل الأجهزه",
   condition: {
  "brandNew": "جديد تمامًا",
  "likeNew": "كالجديد",
  "usedGood": "مستعمل - بحالة جيدة",
  "usedNeedsRepair": "مستعمل - يحتاج إلى تصليح",
  "notWorking": "لا يعمل"
},

  "signUp": "تسجيل جديد",
  "registrationFailed": "فشل التسجيل. يرجى التحقق من المدخلات.",
  "somethingWentWrong": "حدث خطأ ما.",
  "firstNameRequired": "الاسم الأول مطلوب",
  "firstNameLettersOnly": "يجب أن يحتوي الاسم الأول على حروف فقط",
  "firstNameMin": "يجب أن يكون الاسم الأول على الأقل 2 أحرف",
  "lastNameRequired": "اسم العائلة مطلوب",
  "lastNameLettersOnly": "يجب أن يحتوي اسم العائلة على حروف فقط",
  "lastNameMin": "يجب أن يكون اسم العائلة على الأقل 2 أحرف",
  "emailRequired": "البريد الإلكتروني مطلوب",
  "emailValid": "يرجى إدخال بريد إلكتروني صالح",
  "passwordRequired": "كلمة المرور مطلوبة",
  "passwordMin": "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
  "passwordLetter": "يجب أن تحتوي كلمة المرور على حرف واحد على الأقل",
  "passwordNumber": "يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
  "passwordConfirmRequired": "يرجى تأكيد كلمة المرور",
  "passwordsMustMatch": "يجب أن تتطابق كلمتا المرور",
  "phoneRequired": "رقم الهاتف مطلوب",
  "phoneNumbersOnly": "يجب أن يحتوي رقم الهاتف على أرقام فقط",
  "phoneMin": "يجب أن يكون رقم الهاتف 11 رقمًا على الأقل",
  "addressRequired": "العنوان مطلوب",
  "addressMin": "يجب أن يكون العنوان 5 أحرف على الأقل",
  "cityRequired": "المدينة مطلوبة",
  "stateRequired": "الولاية مطلوبة",
  "zipRequired": "الرمز البريدي مطلوب",
  "zipDigits": "يجب أن يكون الرمز البريدي بين 4 إلى 10 أرقام",
  "countryRequired": "البلد مطلوب",
  "alreadyHaveAccount": "هل لديك حساب بالفعل؟",
  "login": "تسجيل الدخول",
  "fields": {
    "first_name": "الاسم الأول",
    "last_name": "اسم العائلة",
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "password_confirmation": "تأكيد كلمة المرور",
    "phone": "رقم الهاتف",
    "address": "العنوان",
    "city": "المدينة",
    "state": "المنطقة / الولاية",
    "ZIP_code": "الرمز البريدي",
    "country": "الدولة"
  },
  "signin": {
    "title": "تسجيل الدخول",
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "submit": "تسجيل الدخول",
    "loading": "جارٍ التحميل...",
    "success": "تم تسجيل الدخول بنجاح",
    "error": "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    "noAccount": "ليس لديك حساب؟",
    "register": "إنشاء حساب"
  },
  "validation": {
    "required": "مطلوب",
    "email": "أدخل بريدًا إلكترونيًا صحيحًا",
    "minChars": "يجب أن يكون على الأقل {{count}} حرفًا"
    
  },
  "addequipment": {
    "title": "إضافة جهاز طبي",
    "titleLabel": "العنوان",
    "titlePlaceholder": "أدخل عنوان الجهاز",
    "descLabel": "الوصف",
    "descPlaceholder": "اكتب وصفًا مختصرًا",
    "priceLabel": "السعر (بالجنيه)",
    "pricePlaceholder": "أدخل سعر الجهاز",
    "conditionLabel": "الحالة",
    "conditionPlaceholder": "اختر حالة الجهاز",
    "confirmFeeMessage": "A platform fee of {{fee}} EGP will be applied. Do you want to proceed?",
  "confirmTitle": "Confirm Listing",
  "confirmYes": "Yes, submit",
  "confirmNo": "No, cancel",
    "condition": {
      "brandNew": "جديد تمامًا",
      "likeNew": "مثل الجديد",
      "usedGood": "مستعمل - بحالة جيدة",
      "usedNeedsRepair": "مستعمل - يحتاج إلى إصلاح",
      "notWorking": "لا يعمل"
    },
    "categoryLabel": "الفئة",
    "categoryPlaceholder": "اختر الفئة",
    "categories": {
      "beds": "أسرة ونقالات المستشفيات",
      "vital": "أجهزة مراقبة العلامات الحيوية",
      "mobility": "معدات دعم الحركة",
      "dental": "معدات العناية بالأسنان",
      "diagnostic": "أدوات التشخيص الأساسية",
      "lab": "أجهزة المختبر والتحاليل",
      "imaging": "أجهزة التصوير والأشعة",
      "respiratory": "أجهزة دعم التنفس",
      "iv": "معدات إعطاء المحاليل",
      "sterilization": "أدوات التعقيم والتطهير",
      "emergency": "معدات الطوارئ والإنعاش",
      "rehabilitation": "أدوات إعادة التأهيل والعلاج",
      "infant": "رعاية الأطفال حديثي الولادة",
      "others": "أخرى"
    },
    "donationLabel": "تبرع",
    "donationPlaceholder": "هل هذا الجهاز تبرع؟",
    "donation": {
      "yes": "نعم، تبرع",
      "no": "لا، للبيع"
    },
    "mainImageLabel": "الصورة الرئيسية",
    "mainImageRequired": "الصورة الرئيسية مطلوبة.",
    "optionalImage": "صورة اختيارية {{num}}",
    "submit": "إرسال",
    "cancel": "إلغاء",
    "loading": "جاري الرفع...",
    "success": "تمت إضافة الجهاز بنجاح!",
    "error": "فشل في إضافة الجهاز.",
    "somethingWrong": "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    
  },
  back: "عودة",
      loadingFailed: "فشل في تحميل البيانات",
      productNotFound: "المنتج غير موجود",
      postedOn: "تاريخ النشر:",
      buyNow: "شراء الآن",
      contactSeller: "التواصل مع البائع",
      contactUnderDevelopment: "خاصية التواصل قيد التطوير",
      additionalImage: "صورة إضافية",
      toggleLang: "English",
      loading: "جاري التحميل...",
      return: "عودة",
      errorMsg: "فشل في تحميل البيانات",
      
  "category": "الفئة",
  "addedBy": "تم الإضافة بواسطة",
  "name": "الاسم",
  "email": "البريد الإلكتروني",
  "phone": "الهاتف",
  "address":"العنوان",
  "productNotFound": "المنتج غير موجود",
  "loadingFailed": "فشل تحميل بيانات المنتج",
  "loading": "جاري التحميل...",
  "return": "رجوع",
  "postedOn": "تاريخ النشر",
  "buyNow": "اشتري الآن",
  "contactSeller": "تواصل مع البائع",
  "additionalImage": "صورة إضافية",
  "feedback": "التعليقات",
  "seller": "البائع",
 
  "Profile":"الصفحه الشخصيه",
  "myProfile": {
    "confirm_delete": "هل أنت متأكد أنك تريد حذف هذا المنتج؟",
    "delete_failed": "فشل في حذف المنتج",
    "product_image": "صورة المنتج",
    "price": "السعر",
    "status": "الحالة",
    "availability": "التوفر",
    "posted_on": "تم النشر في",
    "marking": "جارٍ التمييز...",
    "mark_as_sold": "تمييز كـ مباع",
    "deleting": "جارٍ الحذف...",
    "delete": "حذف",
    "no_products": "ليس لديك أي منتجات مدرجة حتى الآن.",
    "survey_form": "نموذج الاستبيان",
    "coming_soon": "{{component}} قادم قريبًا",
    "wallet_balance": "رصيد المحفظة",
    "guest_user": "مستخدم زائر",
    "browsing_as_guest": "تصفح كمستخدم زائر",
    "email": "البريد الإلكتروني",
    "phone": "الهاتف",
    "wallet": "المحفظة",
    "joined": "تاريخ الانضمام",
    "listings": "القوائم",
    "messages": "الرسائل",
    "orders": "الطلبات",
    "request": "طلب",
    "survey": "استبيان",
    "community": "المجتمع",
    "ai_suggestion": "اقتراحات الذكاء الاصطناعي",
"no_ai_suggestions": "لم يتم العثور على اقتراحات",
"price": "السعر",
"category": "الفئة",
"available": "التوفر"
  },
  "survey": {
    "age": "العمر",
    "gender": "الجنس",
    "select": "اختر",
    "male": "ذكر",
    "female": "أنثى",
    "primary_medical_condition": "الحالة الطبية الأساسية",
    "health_care_provider": "مقدم الرعاية الصحية",
    "mobility_level": "مستوى الحركة",
    "medical_equipment": "المعدات الطبية",
    "duration_of_need": "مدة الحاجة",
    "submitting": "جارٍ الإرسال...",
    "submit": "إرسال",
    "equipment": {
      "beds": "أسرة ومستلقيات المستشفى",
      "monitoring": "أجهزة مراقبة العلامات الحيوية",
      "mobility_support": "معدات دعم الحركة",
      "dental": "معدات العناية بالأسنان",
      "diagnostics": "أدوات التشخيص الأساسية",
      "lab": "أجهزة المختبر والاختبارات",
      "imaging": "أجهزة التصوير والأشعة",
      "respiratory": "أجهزة دعم التنفس",
      "iv_fluid": "الأجهزة الخاصة بالتنقيط والسوائل الوريدية",
      "sterilization": "أدوات التعقيم والتطهير",
      "emergency": "معدات الطوارئ ودعم الحياة",
      "rehabilitation": "أدوات التأهيل والعلاج",
      "infant_care": "رعاية الرضع والأطفال حديثي الولادة",
      "others": "أخرى"
    }
  },
  "filterProducts": "تصفية المنتجات",
 "allCategories": "كل الفئات",
  "mobilitySupport": "معدات دعم الحركة",
  "emergencySupport": "معدات الطوارئ ودعم الحياة",
  "walker": "مشاية",
  "hospitalBeds": "أسرة المستشفيات والنقالات",
  "respiratorySupport": "أجهزة دعم التنفس",
  "labTesting": "أجهزة المعمل والاختبار",
  "vitalSigns": "أجهزة مراقبة العلامات الحيوية",
  "rehabilitation": "أدوات التأهيل والعلاج",
  "dentalCare": "معدات العناية بالأسنان",
  "allConditions": "كل الحالات",
  "brandNew": "جديد تمامًا",
  "likeNew": "كالجديد",
  "usedGood": "مستعمل - جيد",
  "usedNeedsRepair": "مستعمل - يحتاج إلى صيانة",
  "notWorking": "لا يعمل",
  "minPrice": "أقل سعر",
  "maxPrice": "أعلى سعر",
  "priceLowToHigh": "السعر من الأقل إلى الأعلى",
  "priceHighToLow": "السعر من الأعلى إلى الأقل",
  "apply": "تطبيق",
  "reset": "إعادة تعيين",
  "noProductsFound": "لا توجد منتجات مطابقة للفلتر المختار.",
  "noTitle": "بدون عنوان",
  "category": "الفئة",
  "condition_2": "الحالة",
  "price": "السعر",
  "na": "غير متوفر",
  
  "donationForm": {
    "header": "طلب تبرع من جمعية خيرية",
    "ngoName": "اسم الجمعية",
    "ngoNameHelp": "أدخل اسم الجمعية الخيرية المقدمة للطلب",
    "itemName": "اسم العنصر",
    "itemNameHelp": "أدخل اسم العنصر المراد التبرع به",
    "description": "الوصف",
    "descriptionHelp": "صف حالة واستخدام العنصر",
    "quantity": "الكمية",
    "quantityHelp": "الحد الأدنى للكمية هو 1",
    "image": "تحميل صورة",
    "imageHelp": "اختياري. فقط PNG أو JPG أو JPEG",
    "submit": "إرسال",
    "cancel": "إلغاء",
    "loading": "جاري الإرسال...",
    "success": "تم إرسال التبرع بنجاح!",
    "error": "فشل في إرسال التبرع. حاول مرة أخرى."
  },
  "contactTitle": "تواصل مع {{name}}",
  "seller": "البائع",
  "loadingMessages": "جاري تحميل الرسائل...",
  "noPreviousMessages": "لا توجد رسائل سابقة.",
  "you": "أنت",
  "defaultMessage": "مرحبًا، أنا مهتم بـ {{title}}. هل لا تزال متاحة؟",
  "sendMessage": "إرسال الرسالة",
  "sending": "جاري الإرسال...",
"reportProblem": "الإبلاغ عن مشكلة",
"describeProblem": "يرجى وصف المشكلة...",
"pleaseWriteSomething": "يرجى كتابة شيء قبل الإرسال.",
"submitReport": "إرسال البلاغ",
"cancel": "إلغاء",
"reportSent": "تم إرسال بلاغك. شكرًا لك!",
"reportFailed": "فشل إرسال البلاغ. حاول مرة أخرى لاحقًا."
,
  "giveFeedback": "أرسل ملاحظاتك",
  "feedbackPlaceholder": "اكتب ملاحظاتك هنا...",
  "feedbackThanks": "شكرًا لملاحظاتك!",
  "enterFeedback": "يرجى كتابة الملاحظات قبل الإرسال.",
  "submit": "إرسال",
  "cancel": "إلغاء",
  
  "report": {
    "title": "لوحة تقارير المسؤول",
    "loading": "جاري تحميل التقارير...",
    "loadError": "فشل تحميل التقارير. الرجاء المحاولة لاحقًا.",
    "noReports": "لا توجد تقارير متاحة.",
    "listHeader": "قائمة التقارير",
    "user": "المستخدم",
    "report": "التقرير",
    "createdAt": "تاريخ الإنشاء"
  },
  
  "missingProductInfo": "معلومات المنتج مفقودة.",
  "failedToLoadCheckout": "فشل في تحميل معلومات الدفع.",
  "pleaseFillFields": "يرجى ملء جميع الحقول المطلوبة بشكل صحيح.",
  "orderSuccessWallet": "تم إتمام الطلب بنجاح!",
  "orderSuccessWalletPartial": "تم إتمام الطلب بنجاح! لقد دفعت {{amount}} دولار من مصدر آخر.",
  "walletPaymentFailed": "فشل الدفع باستخدام المحفظة. يرجى تجربة طريقة دفع أخرى.",
  "orderSuccessCOD": "تم تقديم الطلب بنجاح (الدفع عند الاستلام)!",
  "addressUpdateFailed": "فشل تحديث العنوان.",
  "checkoutFailed": "حدث خطأ أثناء إتمام الدفع. يرجى المحاولة مرة أخرى.",
  "loadingCheckout": "جارٍ تحميل معلومات الدفع...",
  "checkoutTitle": "الدفع",
  "shippingInfo": "معلومات الشحن",
  "fullName": "الاسم الكامل",
  "email": "البريد الإلكتروني",
  "address": "العنوان",
  "city": "المدينة",
  "state": "المحافظة",
  "zipCode": "الرمز البريدي",
  "zipNumeric": "يجب أن يكون الرمز البريدي رقمياً",
  "country": "الدولة",
  "selectCountry": "اختر الدولة",
  "egypt": "مصر",
  "paymentMethod": "طريقة الدفع",
  "wallet": "المحفظة",
  "balance": "الرصيد",
  "add": "أضف",
  "cashOnDelivery": "الدفع عند الاستلام",
  "processing": "جارٍ المعالجة...",
  "placeOrder": "إتمام الطلب",
  "orderSummary": "ملخص الطلب",
  "subtotal": "المجموع الفرعي",
  "shipping": "الشحن",
  "total": "الإجمالي",
  "sellerInfo": "معلومات البائع",
  "name": "الاسم",
  
  "maintenanceRequest": "طلب صيانة",
  "title": "العنوان",
  "productDesc": "وصف المنتج",
  "problemDesc": "وصف المشكلة",
  "phone": "رقم الهاتف",
  "address": "العنوان",
  "submitRequest": "إرسال الطلب",
    "confirmMaintenance": "رسوم الصيانة 300 جنيه. هل تريد المتابعة؟"
,
  
  "maintenance": {
    "header": "تقارير الصيانة",
    "loading": "جاري تحميل تقارير الصيانة...",
    "loadError": "فشل تحميل تقارير الصيانة. الرجاء المحاولة لاحقًا.",
    "noReports": "لا توجد تقارير صيانة حالياً.",
    "listHeader": "قائمة تقارير الصيانة",
    "user": "اسم المستخدم",
    "title": "عنوان المنتج",
    "address": "العنوان",
    "phone": "رقم الهاتف",
    "productDesc": "وصف المنتج",
    "problemDesc": "وصف المشكلة",
    "createdAt": "تاريخ الإنشاء"
  },
  
"AllOrders":"كل الطلبات",
"ShowMantiance":"أظهار طلبات الصبانه",
"SubscriptionPage":" الاشتراكات",
"SubscriptionRequest":" طلب اشتراكات",

  "orders": {
    "title": "جميع الطلبات",
    "loading": "جاري تحميل الطلبات...",
    "loadError": "فشل تحميل الطلبات. الرجاء المحاولة لاحقًا.",
    "noOrders": "لا توجد طلبات حالياً.",
    "listHeader": "قائمة الطلبات",
    "orderId": "رقم الطلب",
    "userId": "رقم المستخدم",
    "productId": "رقم المنتج",
    "condition": "الحالة",
    "subscription": "اشتراك",
    "payment": "دفع",
    "date": "تاريخ الطلب"
  },
  
  "subscription": {
    "title": "معلومات الاشتراك",
    "detailsHeader": "تفاصيل اشتراك المستخدم",
    "id": "الرقم التعريفي",
    "name": "الاسم",
    "email": "البريد الإلكتروني",
    "phone": "الهاتف",
    "wallet": "المحفظة",
    "address": "العنوان",
    "city": "المدينة",
    "country": "الدولة",
    "created_at": "تاريخ الإنشاء",
    "loading": "جاري تحميل بيانات الاشتراك...",
    "error": "فشل في تحميل معلومات الاشتراك"
  },
  
  "DonationRequests": "طلبات التبرع من الجمعيات",
  "viewAllDonationRequests": "عرض جميع طلبات التبرع من الجمعيات",
  "description": "الوصف",
  "ngoName": "اسم الجمعية",
  "quantity": "الكمية",
  "status": "الحالة",
  "free": "مجانًا",
  "noDescription": "لا يوجد وصف",
  "donateOne": "تبرع +1",
  "donationSuccess": "تم التبرع بنجاح!",
  "donationFailed": "فشل في التبرع. حاول مرة أخرى.",
    "AcceptNgoRequest":"قبول طلبات التبرع من الجمعيات"
, "inspection": {
    "title": "فحص",
    "heading": "خدمة الفحص",
    "description": "نحن نقدم خدمة فحص موثوقة للمعدات لضمان الجودة والسلامة.",
    "fee": "الرسوم: ٧٠ جنيه",
    "contactMessage": "إذا كنت ترغب في فحص جهاز، يرجى التواصل معنا:",
    "contactButton": "تواصل معنا على MedTrade@gmail.com"
  },
  "wallet": {
    "title": "ادفع عبر Paymob",
    "emailLabel": "البريد الإلكتروني",
    "emailPlaceholder": "أدخل بريدك الإلكتروني",
    "amountLabel": "المبلغ (بالجنيه)",
    "amountPlaceholder": "أدخل المبلغ المراد دفعه",
    "payNow": "ادفع الآن",
    "loading": "جارٍ المعالجة...",
    "validationError": "يرجى إدخال بريد إلكتروني صحيح ومبلغ صالح",
    "paymentFailed": "فشل الدفع",
    "unknownError": "حدث خطأ غير معروف",
    "urlError": "لا يوجد بريد إلكتروني أو مبلغ صالح في الرابط"
  } ,"WalletRecharge":"شحن المحفظه"  },
        
      }
    },
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
